"""add dep_type

Revision ID: 14b5aa5aaabf
Revises: 498d366138ed
Create Date: 2023-06-21 11:20:20.186458

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14b5aa5aaabf"
down_revision = "498d366138ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_type", sa.Column("dep_type", sa.String(length=50), nullable=True)
    )
    order_dep_types = [
        {"name": "Заказ на баню", "dep_type": "MAIN"},
        {"name": "Заявка на сруб", "dep_type": "DEPEND"},
        {"name": "Заявка на брак сруба", "dep_type": "DEFECT"},
    ]
    bind = op.get_bind()
    for it in order_dep_types:
        op.execute(
            f'UPDATE order_type SET dep_type = \'{it["dep_type"]}\' WHERE name LIKE \'{it["name"]}\''
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_type", "dep_type")
    # ### end Alembic commands ###
