"""add order status update entity

Revision ID: 498d366138ed
Revises: ea76307c5121
Create Date: 2023-06-18 20:05:43.696812

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "498d366138ed"
down_revision = "ea76307c5121"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_status_update",
        sa.Column("user", sa.String(length=100), nullable=True),
        sa.Column("old_status", sa.String(length=100), nullable=True),
        sa.Column("new_status", sa.String(length=100), nullable=True),
        sa.Column("order_id", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_update_id"), "order_status_update", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_status_update_id"), table_name="order_status_update")
    op.drop_table("order_status_update")
    # ### end Alembic commands ###
