"""rename defect order

Revision ID: 6534e44e3ddc
Revises: 14b5aa5aaabf
Create Date: 2023-06-21 17:43:12.629373

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6534e44e3ddc'
down_revision = '14b5aa5aaabf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    order_dep_types = [
        {'name': 'Заказ на баню', 'dep_type': 'MAIN'},
        {'name': 'Заявка на сруб', 'dep_type': 'DEPEND'},
        {'name': 'Заявка на брак', 'dep_type': 'DEFECT'},
    ]
    bind = op.get_bind()
    for it in order_dep_types:
        op.execute(f'UPDATE order_type SET dep_type = \'{it["dep_type"]}\' WHERE name LIKE \'{it["name"]}\'')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
