"""parent nullable

Revision ID: ea76307c5121
Revises: fdc94f2d9c8e
Create Date: 2023-06-14 13:08:06.270341

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea76307c5121"
down_revision = "fdc94f2d9c8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order", "parent_order_id", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order", "parent_order_id", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
