"""order links

Revision ID: fdc94f2d9c8e
Revises: 390693bb4863
Create Date: 2023-06-14 13:00:29.650590

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fdc94f2d9c8e"
down_revision = "390693bb4863"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_order_link_id", table_name="order_link")
    op.drop_table("order_link")
    op.drop_index("ix_order_link_type_id", table_name="order_link_type")
    op.drop_table("order_link_type")
    op.add_column(
        "order", sa.Column("parent_order_id", sa.String(length=50), nullable=False)
    )
    op.create_foreign_key(None, "order", "order", ["parent_order_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_column("order", "parent_order_id")
    op.create_table(
        "order_link_type",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="order_link_type_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_order_link_type_id", "order_link_type", ["id"], unique=False)
    op.create_table(
        "order_link",
        sa.Column(
            "order_left_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "order_right_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "link_type_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["link_type_id"],
            ["order_link_type.id"],
            name="order_link_link_type_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["order_left_id"], ["order.id"], name="order_link_order_left_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["order_right_id"], ["order.id"], name="order_link_order_right_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="order_link_pkey"),
    )
    op.create_index("ix_order_link_id", "order_link", ["id"], unique=False)
    # ### end Alembic commands ###
