repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: app/migrations
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
    -   id: mypy
        entry: mypy app
        pass_filenames: false
        verbose: true
        additional_dependencies: [
            pydantic==1.10.5,
            sqlalchemy==2.0.12,
            types-aiofiles==22.1.0.9,
            types-paramiko==3.0.0.4,
            types-passlib==1.7.7.10,
            types-toml==0.10.8.5,
            types-python-jose==3.3.4.5,
            types-psutil==5.9.5.9,
            types-requests==2.28.11.15,
            types-pytz==2022.7.1.2
        ]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/python-poetry/poetry
    rev: 1.3.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
      - id: poetry-export
        args: ["--with", "dev", "-f", "requirements.txt", "-o", "requirements-dev.txt", "--without-hashes"]
