version: "3.9"
services:
  db:
    restart: unless-stopped
    container_name: sem-db
    image: postgres:13
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=1GB"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=sem_data
    volumes:
      - ../.database:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} -d sem_data
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  backend:
    restart: unless-stopped
    container_name: sem-backend
    build:
      context: ..
      args:
        - WORKERS=1
        - RELOAD=1
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-DEV}
      - DATABASE_URI=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/sem_data
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-*}
    volumes:
      - ../app:/backend/app
    ports:
      - "5010:5000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
      - keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  keycloak:
    image: jboss/keycloak:16.1.1
    restart: always
    container_name: sem-keycloak
    volumes:
      - ../.keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: sem_data
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_PORT: 5432
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - '8085:8080'
    links:
      - db
    depends_on:
      db:
        condition: service_healthy