version: "3.9"
services:
  db:
    restart: unless-stopped
    container_name: sem-db
    image: postgres:13
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=1GB"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=sem_data
    volumes:
      - ../.database:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} -d sem_data
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


  backend:
    restart: unless-stopped
    container_name: sem-backend
    build:
      context: ..
      args:
        - WORKERS=1
        - RELOAD=1
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-DEV}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-http://localhost:5173}
      - DATABASE_URI=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/sem_data
      - KEYCLOAK_URL_EXTERNAL=${KEYCLOAK_URL_EXTERNAL:-http://localhost:8085}
      - KEYCLOAK_URL=${KEYCLOAK_URL:-http://keycloak:8080}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-MPI}
      - KEYCLOAK_CLIENT_ID_FRONT=${KEYCLOAK_CLIENT_ID_FRONT:-frontend-client}
      - KEYCLOAK_CLIENT_ID_SERIVCE=${KEYCLOAK_CLIENT_ID_SERIVCE:-service-client}
      - KEYCLOAK_CLIENT_SECRET_SERIVCE=${KEYCLOAK_CLIENT_SECRET_SERIVCE}
    volumes:
      - ../app:/backend/app
    ports:
      - "5010:5000"
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    links:
      - db
      - keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    restart: always
    container_name: sem-keycloak
    volumes:
      - ../keycloak/import:/opt/keycloak/data/import
      - ../keycloak/themes:/opt/keycloak/themes
      - ../.keycloak:/opt/keycloak/data/h2
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_PROXY: passthrough
    ports:
      - '8085:8080'
    healthcheck:
      test: curl --head -fsS http://localhost:8080/health/ready
      interval: 5s
      timeout: 5s
      retries: 15
